# Generated by Django 2.2.12 on 2020-08-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceevent',
            name='distance',
            field=models.FloatField(),
        ),
    ]
