# Generated by Django 2.2.12 on 2020-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200828_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('employee_id', models.CharField(max_length=36)),
                ('employee_name', models.CharField(max_length=36)),
                ('temperature', models.IntegerField()),
                ('breathing', models.BooleanField()),
                ('cough', models.BooleanField()),
                ('body_pain', models.BooleanField()),
                ('throat_pain', models.BooleanField()),
            ],
        ),
    ]
