# Generated by Django 2.2.12 on 2020-08-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200829_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traceevent',
            old_name='date',
            new_name='first_timestamp',
        ),
        migrations.RenameField(
            model_name='traceevent',
            old_name='distance',
            new_name='max_distance',
        ),
        migrations.RemoveField(
            model_name='traceevent',
            name='issue',
        ),
        migrations.AddField(
            model_name='traceevent',
            name='last_timestamp',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='traceevent',
            name='min_distance',
            field=models.FloatField(default=2.3),
            preserve_default=False,
        ),
    ]
