# Generated by Django 2.2.12 on 2020-08-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200829_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceevent',
            name='covid_risk',
            field=models.CharField(choices=[('HIGH_RISK', 'HIGH RISK'), ('MEDIUM_RISK', 'MEDIUM_RISK'), ('LOW_RISK', 'LOW_RISK')], max_length=8),
        ),
    ]
