# Generated by Django 2.2.12 on 2020-08-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200829_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceevent',
            name='device_detail',
            field=models.ForeignKey(default='8ec76ea3-6668-48da-9866-fcf5c4315204', on_delete=django.db.models.deletion.CASCADE, related_name='device_wear_by', to='api.RegisterDevice'),
            preserve_default=False,
        ),
    ]
