# Generated by Django 2.2.12 on 2020-08-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_traceevent_device_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traceevent',
            name='device_detail',
        ),
        migrations.AlterField(
            model_name='traceevent',
            name='partner_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_wear_by_partner', to='api.RegisterDevice'),
        ),
        migrations.AlterField(
            model_name='traceevent',
            name='self_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_wear_by_self', to='api.RegisterDevice'),
        ),
    ]
