# Generated by Django 2.2.12 on 2020-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200829_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceevent',
            name='partner_emp_id',
            field=models.CharField(default='vishnu123', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceevent',
            name='partner_emp_name',
            field=models.CharField(default='dinesh123', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceevent',
            name='self_emp_id',
            field=models.CharField(default='vishnu', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceevent',
            name='self_emp_name',
            field=models.CharField(default='dinesh', max_length=36),
            preserve_default=False,
        ),
    ]
